# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macos-11(macos-latest)'

steps:

  - task: FlutterInstall@0
    inputs:
      mode: 'auto'
      channel: 'stable'
      version: 'latest'

  - task: FlutterCommand@0
    inputs:
      projectDirectory: '.'
      arguments: 'pub get'

  - task: FlutterBuild@0
    inputs:
      target: 'apk'
      projectDirectory: '.'
      debugMode: true
  
  - task: FlutterBuild@0
    inputs:
      target: 'web'
      projectDirectory: '.'

  - task: FlutterAnalyzeTask@0
    inputs:
      projectDirectory: '.'


  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)'
      publishLocation: 'pipeline'